---
name: SignTransfer
version:1.0
api: 1.0.0
author: TonyDroidd
main: TDroidd\SignTransfer\Main
description: Complement for use FastTransfer plugin with signs.
website: https://github.com/TonyDroidd/SignTransfer
